(part "SI2301CDS-T1-BE3"
    (packageRef "SOT95P237X112-3N")
    (interface
        (port "1" (symbPinId 1) (portName "G") (portType INOUT))
        (port "2" (symbPinId 2) (portName "S") (portType INOUT))
        (port "3" (symbPinId 3) (portName "D") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "78-SI2301CDS-T1-BE3")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Vishay-Siliconix/SI2301CDS-T1-BE3?qs=CiayqK2gdcJNFARNd%252BC6jg%3D%3D")
    (property "Manufacturer_Name" "Vishay")
    (property "Manufacturer_Part_Number" "SI2301CDS-T1-BE3")
    (property "Description" "MOSFET P-CHANNEL 20-V (D-S)")
    (property "Datasheet_Link" "https://www.arrow.com/en/products/si2301cds-t1-be3/vishay?region=nac")
    (property "symbolName1" "SI2301CDS-T1-BE3")
)
