(part "TPS22969DNYT"
    (packageRef "TPS22969DNYT")
    (interface
        (port "1" (symbPinId 1) (portName "VIN_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "VIN_2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "VBIAS") (portType INOUT))
        (port "4" (symbPinId 4) (portName "ON") (portType INOUT))
        (port "5" (symbPinId 5) (portName "GND") (portType INOUT))
        (port "6" (symbPinId 6) (portName "VOUT_1") (portType INOUT))
        (port "7" (symbPinId 7) (portName "VOUT_2") (portType INOUT))
        (port "8" (symbPinId 8) (portName "VOUT_3") (portType INOUT))
        (port "9" (symbPinId 9) (portName "VIN_3") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "595-TPS22969DNYT")
    (property "Mouser_Price/Stock" "https://www.mouser.com/Search/Refine.aspx?Keyword=595-TPS22969DNYT")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "TPS22969DNYT")
    (property "Description" "5.5V, 6A, 4.4m Load Switch with Quick Output Discharge")
    (property "Datasheet_Link" "http://www.ti.com/lit/gpn/TPS22969")
    (property "symbolName1" "TPS22969DNYT")
)
